---
- name: Handle Vault events and fetch Vault secret
  hosts: all
  sources:
    - name: vault-events
      webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Vault event triggers Vault secret deployment
      condition: >
        event.payload is defined and
        event.payload.secret_path is defined and
        event.payload.target_host is defined
      action:
        run_job_template:
          name: deploy-secret
          organization: Default
          job_args:
            vault_secret_path: "{{ event.payload.secret_path }}"
            target_host: "{{ event.payload.target_host }}"
