---
- name: Handle Vault events and fetch Vault secret
  hosts: all
  match_multiple_rules: true
  sources:
    - ansible.eda.azure_service_bus:
        queue_name: vault-events
        conn_str: "{{ servicebus_connection_string }}"

  rules:
    - name: Vault event triggers Vault secret deployment
      condition:
        all:
          - event.body.data.event_type == "kv-v2/data-write"
          - event.body.data.event.metadata.modified == "true"
          - event.body.data.event.metadata.path == "secret/data/demo-secret"
      action:
        run_job_template:
          name: Vault EDA Demo Job Template
          organization: Vault EDA Demo

    - name: Log
      condition: true
      actions:
        - print_event:
            pretty: true
