FROM python:3.12-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive
ENV ANSIBLE_HOME=/runner/.ansible
ENV ANSIBLE_COLLECTIONS_PATH=/usr/share/ansible/collections
ENV ANSIBLE_GALAXY_CACHE_DIR=/runner/.ansible/galaxy_cache
ENV ANSIBLE_LOCAL_TEMP=/runner/.ansible/tmp

# System requirements for ansible-rulebook
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      openjdk-17-jre-headless \
      git \
      gcc \
      libffi-dev \
      libssl-dev \
      openssh-client \
      ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN python -m pip install --upgrade pip

# Python deps for rulebooks
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# EDA collection
COPY requirements.yaml /tmp/requirements.yaml
RUN ansible-galaxy collection install -r /tmp/requirements.yaml

# Create own runner directory
RUN mkdir -p /runner/.ansible/{tmp,galaxy_cache} \
 && chgrp -R 0 /runner \
 && chmod -R g+rwX /runner

WORKDIR /runner
