FROM registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest

# Python Dependencies (Vault, Events, JSON handling)
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Ansible Collections
COPY requirements.yml /tmp/requirements.yml
RUN ansible-galaxy collection install -r /tmp/requirements.yml

# Default working directory
WORKDIR /runner