---
- name: Fetch secret from Vault and write to host
  hosts: all
  gather_facts: false

  tasks:
    - name: Write secret to file
      ansible.builtin.copy:
        content: "{{ demo_secret }}"
        dest: "/home/ansible/demo_secret"
        owner: root
        group: root
        mode: "0600"
